#! /bin/sh

sxhkd &

# ws1=desktop
# ws2=browse
# ws3=code
# ws4=edit
# ws5=cli
# ws6=media
# ws7=communicate
# ws8=8
# ws9=9
# ws0=0

bspc config border_width        1
bspc config window_gap        	0
bspc config top_padding 		0

# bspc config border_width		2
# bspc config window_gap        5
# bspc config top_padding 		30

#Borders and gaps
bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

bspc config focus_follows_pointer   true
bspc config auto_alternate          true
bspc config active_border_color "#3F4B9C"
bspc config focused_border_color "#3F4B9C"
bspc config presel_border_color "#181818"
bspc config urgent_border_color "#C90515"
bspc config focused_locked_border_color "#8c644c"
bspc config normal_frame_opacity 0.0
bspc config focused_frame_opacity 0.1

# Border colors
bspc config normal_border_color "#484848"
bspc config focused_border_color "#1F8999"
bspc config urgent_border_color "#B58900"
bspc config presel_border_color "#26E2FF"

bspc monitor LVDS1 -d I II III IV VI V VII VIII IX X
# bspc monitor VGA1 -d I VI X
#bspc monitor LVDS1 -d $ws1 $ws2 $ws3 $ws4 $ws5 $ws6 $ws7 $ws8 $ws9 $ws0

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true

#wmname LG3D
bspc rule -a Firefox desktop=^2
bspc rule -a Firefox Developer Edition desktop=^2
bspc rule -a Google-chrome  desktop=^2
bspc rule -a Chromium desktop=^2
bspc rule -a TelegramDesktop desktop=^3 
bspc rule -a Skype desktop=^3 
bspc rule -a Transmission-gtk desktop=^3
bspc rule -a Subl3 desktop=^4
bspc rule -a Atom desktop=^4
bspc rule -a QtCreator desktop=4
bspc rule -a QGIS3 desktop=^5
bspc rule -a Qgis desktop=^5
bspc rule -a Gimp desktop=^5
bspc rule -a TeXstudio desktop=^5
bspc rule -a Inkscape desktop=^5
bspc rule -a Merkaartor  desktop=^6
bspc rule -a org-openstreetmap-josm-gui-MainApplication desktop=^6
bspc rule -a org-openstreetmap-josm-Main desktop=^6
bspc rule -a libreoffice-writer desktop=^7 state=tiled 
bspc rule -a Zathura desktop=^7 state=tiled
bspc rule -a Nautilus  desktop=^8
bspc rule -a Thunar  desktop=^8
bspc rule -a Audacity desktop=^9 focus=on
bspc rule -a Thunderbird desktop=^9
bspc rule -a MPlayer desktop=^9 focus=on state=fullscreen
bspc rule -a Zotero desktop=^10
bspc rule -a Lxappearance state=floating center=true
bspc rule -a SimpleScreenRecorder state=floating center=true

# polybar
# $HOME/.config/polybar/launch.sh

~/.fehbg &
lxappearance
firefox
# ~/bin/scratch

# moved to xinitrc
# compton &

# Bar configurations
# $HOME/.config/polybar/launch.sh
xrdb ~/.Xresources

